[ADD] Sign up, Sign in, social login, profile, login required 기능 구현
wecode-bootcamp-korea/Wepick-backend pull request #4
Opened 2020-06-17 13:17 UTC by NHK721

Wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
Sign up, Sign in, social login, profile, login required 기능 구현 및 테스트완료         
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
Sign up, Sign in, social login, profile, login required 기능 구현 및 테스트완료    

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [X] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-06-17 13:18 UTC, soheon-lee commented on account/tests.py
> +from .views         import SocialLoginView
import 순서 맞춰주세요

django module 따로
내가 만든 module 따로

2020-06-17 13:19 UTC, soheon-lee commented on account/tests.py
> +class EmailCheckTest(TestCase):
import 이후 class 시작할 때는 한 줄씩 간격 넣어주세요

2020-06-17 13:19 UTC, soheon-lee commented on account/tests.py
> +    def tearDown(self):
함수 정의할 때 한 줄씩 간격 넣어주세요

2020-06-17 13:20 UTC, soheon-lee commented on account/tests.py
> +
의미 없는 공백 지워주세요

2020-06-17 13:21 UTC, soheon-lee commented on account/tests.py
> +    def tearDown(self):
함수간 간격 한 줄씩 띄워주세요

2020-06-17 13:21 UTC, soheon-lee commented on account/views.py
> +            return func(self, request, *args, **kwargs)
간격 맞춰주세요

2020-06-17 13:23 UTC, soheon-lee commented on account/views.py
> +            return JsonResponse({'message':'ALREADY_EXIST'}, status=400)
if not 조건문 if 조건문으로 변경하고 로직 수정해주세요

2020-06-17 13:24 UTC, soheon-lee commented on account/views.py
> +            return JsonResponse({'access_token': token}, status = 200)
else를 사용하지 않아도 되는 구조 수정해주세요

2020-06-17 13:26 UTC, soheon-lee commented on account/views.py
> +        career_id = data['career_id']).save()
`Profile(
    sub_category_id = data['sub_category_id'],
    main_category_id = data['main_category_id'],
).save()`

2020-06-17 13:26 UTC, soheon-lee commented on account/views.py
> +        career_id = data['career_id']).save()
.save() 아랫줄로 분리해주시고, 속성들은 한 칸씩 더 들여써주세요

2020-06-17 13:27 UTC, soheon-lee commented on account/views.py
> +        return JsonResponse({'message': 'save'}, status=200)
'SAVED'로 수정해주세요

2020-06-17 13:27 UTC, soheon-lee commented on account/views.py
> +        if Account.objects.filter(google_id = user_email).exists():
코드 간격 다 맞춰주세요

2020-06-17 13:27 UTC, soheon-lee commented on account/views.py
> +                return JsonResponse({'message': '6자리 이상 입력하세요'}, status=400)
'PASSWORD_TOO_SHORT' 등으로 바꿔주세요

2020-06-17 13:28 UTC, soheon-lee commented on account/views.py
> +from job.models import MainCategory, SubCategory
import 순서 맞춰주세요

2020-06-17 13:28 UTC, soheon-lee commented on account/views.py
> +from .models import Account, Career, Profile
여러개의 클래스를 import 할 때는 한 개의 클래스당 한 줄씩 다 분리해주세요

2020-06-17 13:28 UTC, soheon-lee commented on account/urls.py
> +from .views import EmailCheckView, SignInView, SignUpView, SocialLoginView, JobCategoryView, CareerView, ProfileView
여러개의 class를 import 할 때에는 한 줄씩 모두 분리해주세요

2020-06-18 06:19 UTC, evergreen-david requested changes

2020-06-18 06:19 UTC, evergreen-david commented on account/views.py
> +        user = request.user.id
user 변수 안쓰는데 정리 부탁 드립니다.

2020-06-18 06:19 UTC, evergreen-david commented on account/views.py
> +            )
```suggestion
        user = Account.objects.create(google_id = user_email)
```

2020-06-18 06:19 UTC, evergreen-david commented on account/views.py
> +            token = jwt.encode({ 'user_id' : user.id }, SECRET_KEY, algorithm='HS256').decode('utf-8')
algorithm도 노출되서 좋지 않습니다. SECRET KEY 처럼 my settings에 넣어서 임포트 해주세요.

2020-06-18 06:19 UTC, evergreen-david commented on account/views.py
> +                        )
들여쓰기 간격은 기본적으로 4칸 입니다. 정리 부탁 드립니다.

2020-06-18 06:19 UTC, evergreen-david commented on account/views.py
> +        return JsonResponse({'message':'SUCCESS'}, status=200)
message : SUCCESS 는 보통 리턴해주지 않습니다. HttpResponse로 status code 만 200으로 리턴해주세요.

2020-06-18 06:19 UTC, evergreen-david commented on account/views.py
> +                return JsonResponse({'message': 'PASSWORD_TOO_SHORT'}, status=400)
여기도 8칸 들어가있는데 전체적으로 정리가 필요할것 같습니다.

2020-06-18 06:19 UTC, evergreen-david commented on account/tests.py
> +
클래스 간격 1줄만 띄워지도록 정리 부탁 드립니다.

2020-06-18 06:19 UTC, evergreen-david commented on account/tests.py
> +
여기도 확인 부탁 드립니다.

2020-06-18 06:24 UTC, evergreen-david requested changes

2020-06-18 06:24 UTC, evergreen-david commented on account/views.py
> +            ).save()
```suggestion
        ).save()
```

2020-06-18 06:24 UTC, evergreen-david commented on account/views.py
> +        return JsonResponse({'message': 'SAVED'}, status=200)
```suggestion
        return HttpResponse(status=200)
```

2020-06-18 07:08 UTC, evergreen-david approved these changes

2020-06-18 07:08 UTC, merged